apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "theia.fullname" . }}
spec:
  {{- range .Values.pvc.accessModes }}
  accessModes:
  - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: {{ .Values.pvc.volumeMode }}