apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart-neemias.labels" . | nindent 4 }}
  {{- if .Values.secret.name }}
  name: {{ .Values.secret.name }}
  {{- else }}
  name: {{ include "chart-neemias.fullname" . }}
  {{- end }}
  {{- if .Values.secret.name }}
  {{- end }}
type: Opaque
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{$val | b64enc | quote }}
{{- end }}

#{{- with .Values.secret.data }}
#data:
#  MONGO_URI: {{ .MONGO_URI | b64enc | quote }}
#  USERNAME: {{ .USERNAME | b64enc | quote }}
#  PASSWORD: {{ .PASSWORD | b64enc | quote }}
#{{- end }}